- name: "Test Netbox IP address module"
  connection: local
  hosts: all
  gather_facts: False

  tasks:
    - name: Get a new available IP inside 192.168.0.0/24
      netbox_ip_address:
        netbox_url: http://192.168.0.130
        netbox_token: 27172995b1a594f5ac038491dd531af73a562479
        data:
          prefix: 192.168.0.0/24
        state: new
    - name: Delete IP address within netbox
      netbox_ip_address:
        netbox_url: http://192.168.0.130
        netbox_token: 27172995b1a594f5ac038491dd531af73a562479
        data:
          address: 192.168.1.10
        state: absent
    - name: Create IP address with several specified options
      netbox_ip_address:
        netbox_url: http://netbox.local
        netbox_token: 27172995b1a594f5ac038491dd531af73a562479
        data:
          family: 4
          address: 192.168.0.20
          vrf: Test
          tenant: Test Tenant
          status: Reserved
          role: Loopback
          description: Test description
          tags:
            - Schnozzberry
        state: present
    - name: Ensure that an IP inside 192.168.0.0/24 is attached to GigabitEthernet1
      netbox_ip_address:
        netbox_url: http://192.168.0.130
        netbox_token: 27172995b1a594f5ac038491dd531af73a562479
        data:
          prefix: 192.168.0.0/24
          vrf: Test
          interface:
            name: GigabitEthernet1
            device: test100
        state: present
    - name: Attach a new available IP of 192.168.0.0/24 to GigabitEthernet1
      netbox_ip_address:
        netbox_url: http://192.168.0.130
        netbox_token: 27172995b1a594f5ac038491dd531af73a562479
        data:
          prefix: 192.168.0.0/24
          vrf: Test
          interface:
            name: GigabitEthernet1
            device: test100
        state: new
