- name: "Test Netbox prefix module"
  connection: local
  hosts: localhost
  gather_facts: False
  collections:
    - netbox_community.ansible_modules
  vars:
    netbox_url: http://192.168.0.160
    netbox_token: 869e49848b645d3b903800ab2d7325725ce1fcb7
  tasks:
    - name: "Create new site"
      netbox_site:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "Ansible Test Site"
        state: present
        validate_certs: false
      register: "site"

