- name: "Test Netbox prefix module"
  connection: local
  hosts: localhost
  gather_facts: False
  collections:
    - netbox_community.ansible_modules
  vars:
    netbox_url: http://netboxldap
    netbox_token: 27172995b1a594f5ac038491dd531af73a562479
  tasks:
    - name: Create prefix within Netbox with only required information
      netbox_prefix:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          prefix: 192.168.5.0/24
        state: present

