- name: "Test Netbox IP address module"
  connection: local
  hosts: all
  gather_facts: False

  tasks:
    - name: Get a new available IP inside 192.168.0.0/24
      netbox_ip_address:
        netbox_url: http://192.168.0.130
        netbox_token: 27172995b1a594f5ac038491dd531af73a562479
        validate_certs: no
        data:
          address: 192.168.1.10
        state: present
      #delegate_to: localhost
